---
- name: Include OS Specific setup tasks
  include: setup-{{ ansible_os_family }}.yml

- name: Install default Logstash conig
  include: config.yml
  when: logstash_default_config

- include: ssl.yml
- include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
