---
- name: Get list of installed plugins.
  command: >
    ./bin/logstash-plugin list
    chdir={{ logstash_dir }}
  register: logstash_plugins_list
  changed_when: false

- name: Install configured plugins.
  command: >
    ./bin/logstash-plugin install {{ item }}
    chdir={{ logstash_dir }}
  with_items: "{{ logstash_install_plugins }}"
  when: "item not in logstash_plugins_list.stdout"
  notify: restart logstash

- name: Download OpenSearch output plugin
  get_url:
    url: "{{ logstash_opensearch_plugin_url }}"
    dest: "/tmp/{{ logstash_opensearch_plugin_name }}"

- name: Install OpenSearch output plugin
  command: >
    ./bin/logstash-plugin install /tmp/{{ logstash_opensearch_plugin_name }}
    chdir={{ logstash_dir }}
  when: "'logstash-output-opensearch' not in logstash_plugins_list.stdout"
  notify: restart logstash
